spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://52.143.181.4:33060/gestoria
    driverClassName: com.mysql.cj.jdbc.Driver
    username: gestor
    password: gestorInventario

    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1800000
      keepalive-time: 60000
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
  mail:
    host: smtp.gmail.com
    port: 587
    username: pavonhueteismael@gmail.com
    password: lyhdqdrwbtqwirhv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  sql:
    init:
      mode: always

logging:
  file:
    name: logs/app.log

jwt:
  jwtSecret: N1o7FZxYt6bR8wL3qECvKJhDsUG9Xz5pWmTyVqLoHaBsIdCfJeK4MvTnRzSaPgQX
  jwtExpirationMs: 86400000
